### ISSUE TITLE
Errors compiling with VS2012

### ISSUE THREAD

**Issue by devds** [john-chapman/im3d#29]
Hi,I am having errors during VS2012 compilation:
for example :
 error C2864: 'Im3d::Vector<T>::m_size' : only static const integral data members can be initialized within a class
 ::m_capacity' : only static const integral data members can be initialized within a class
 ): error C2864: 'Im3d::Vector<T>::m_data' : only static const integral data members can be initialized within a class
and many others
How to fix?

**Comment by john-chapman** [comment]
Hi,

Non-static data data member initializers are a C++11 feature. VS2012 has [quite poor support for C++11](https://msdn.microsoft.com/en-us/library/hh567368.aspx), but if you really need it to work you could hack Im3d by moving the initialization of these variables to the class constructors. You will also need to patch the use of `alignof` as I think this is also not supported in VS2012.

**Comment by john-chapman** [comment]
Closing this issue unless there are any further questions.
