### ISSUE TITLE
plane drawing issue in local mode

### ISSUE THREAD

**Issue by shadd3** [john-chapman/im3d#35]
Hi
Some planes in local "translation mode" are not drawn
I have fixed that by a workaround (see below); but i guess there is a better solution
Regards

world mode
![image](https://user-images.githubusercontent.com/18207679/46750192-b9051680-ccb7-11e8-982b-92c6a18929dd.png)
local mode
![image](https://user-images.githubusercontent.com/18207679/46750222-c6220580-ccb7-11e8-845f-0e587092afd2.png)

workaround:  color.setA(1.0 /* color.getA() * aligned */); 

```
void Context::gizmoPlaneTranslation_Draw(Id _id, const Vec3& _origin, const Vec3& _normal, float _worldSize, Color _color)
{
	Vec3 viewDir = m_appData.m_projOrtho
		? m_appData.m_viewDirection
		: Normalize(m_appData.m_viewOrigin - _origin)
		;
	float aligned = fabs(Dot(_normal, viewDir));
	aligned = Remap(aligned, 0.1f, 0.2f);
	Color color = _color;
	color.setA(1.0 /*color.getA() * aligned*/); <=== HERE
	pushColor(color);
		pushAlpha(_id == m_hotId ? 0.7f : 0.1f * getAlpha());
			DrawQuadFilled(_origin, _normal, Vec2(_worldSize));
		popAlpha();
		DrawQuad(_origin, _normal, Vec2(_worldSize));
	popColor();
}

```
result in local mode
![image](https://user-images.githubusercontent.com/18207679/46750341-008ba280-ccb8-11e8-83ac-b0524a9dda69.png)

**Comment by john-chapman** [comment]
Hi - thanks very much for reporting this. The root cause of the issue was that translation planes expect the local matrix to be pushed however the view-dependent fadeout wasn't using this information. Fixed in https://github.com/john-chapman/im3d/commit/50585c06ceb89cb7d7343e0c855024ee4b970844.
