### ISSUE TITLE
Add IM3D_API macro for dll export

### ISSUE THREAD

**Issue by vlmillet** [john-chapman/im3d#37]
Hi John, Im3d cannot be exported inside its own dll for better modularization, it would be nice if you could add some **IM3D_API** macro in front of your API functions and in front of public classes such as Context or AppData.
Thanks!

**Comment by john-chapman** [comment]
Hi Vivien - you're right, I meant to do this a while ago. I'll put it at the top of the todo list 😉. Thanks!

**Comment by john-chapman** [comment]
@vlmillet There's now a pull request with the relevant changes [here](https://github.com/john-chapman/im3d/pull/38) if you want to take a quick look.
