### ISSUE TITLE
wrong behavior when scale the model

### ISSUE THREAD

**Issue by kalluwa** [john-chapman/im3d#42]
i am testing this great tool, but it behaves strange when scale the model . as the image display

![gizmoscaleerror](https://user-images.githubusercontent.com/9412335/86869894-f3f4e200-c109-11ea-8ed5-ce369af1646f.gif)

(mouse pos in the image(there is an offset) is not the real position due to the recording software)
using the lastest codebase

**Comment by john-chapman** [comment]
Hi - thanks for reporting this, I'll look into it ASAP.

In the meantime, you can workaround the issues by setting `m_flipGizmoWhenBehind = false` on the `AppData` struct.

**Comment by kalluwa** [comment]
thanks a lot

**Comment by john-chapman** [comment]
Actually it was a simple fix, thanks again for reporting this.
