### ISSUE TITLE
Custom include for im3d_config.h

### ISSUE THREAD

**Issue by jlaumon** [john-chapman/im3d#49]
Hey John!

How about adding something like `IMGUI_USER_CONFIG`, which allows including a different file in case you don't want to modify im3d_config.h? (If you use im3d as a submodule for example.)

```c++
// Configuration file with compile-time options (edit imconfig.h or '#define IMGUI_USER_CONFIG "myfilename.h" from your build system')
#ifdef IMGUI_USER_CONFIG
#include IMGUI_USER_CONFIG
#endif
#if !defined(IMGUI_DISABLE_INCLUDE_IMCONFIG_H) || defined(IMGUI_INCLUDE_IMCONFIG_H)
#include "imconfig.h"
#endif
```

I can make a PR if you're interested.

Cheers

**Comment by john-chapman** [comment]
Ah, good idea! I'm not sure about the utility of the `IMGUI_DISABLE_INCLUDE_IMCONFIG_H`/`IMGUI_INCLUDE_IMCONFIG_H` macros, I'd prefer something like this:
```
#ifdef IM3D_CONFIG
   #include IM3D_CONFIG
#else
   #include "im3d_config.h"
#endif
```
Could always add those extra control macros if there's ever a use case for them. 

If you've got time a PR would be cool! 

Cheers.
