### ISSUE TITLE
Plug into existing application

### ISSUE THREAD

**Issue by jacquesvaneeden** [john-chapman/im3d#53]
I have an existing opengl / CUDA app doing volumetric rendering, now need to add grids, rulers and text. Since I am not a opendgl fundi you lid seems quite ideal for my development. 

May I please get a little guidance here on how to plug im3D into existing systems and drawing to already defined lg screen textures
Thanks

**Comment by john-chapman** [comment]
Please refer to the "Integration" section of [README.md](https://github.com/john-chapman/im3d#readme). You can also find a complete OpenGL integration example in [examples/OpenGL33/](https://github.com/john-chapman/im3d/blob/master/examples/OpenGL33/im3d_opengl33.cpp).
